// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.engine;

public final class PublicInterfaceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggersPublic.server.PublicInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getCustomerDAO_0;
    private static java.lang.reflect.Method $method_getProjectDAO_1;
    private static java.lang.reflect.Method $method_getUserDAO_2;
    private static java.lang.reflect.Method $method_getUserInfoDAO_3;
    
    static {
	try {
	    $method_getCustomerDAO_0 = se.kyh.ad10.timeloggersPublic.server.PublicInterface.class.getMethod("getCustomerDAO", new java.lang.Class[] {});
	    $method_getProjectDAO_1 = se.kyh.ad10.timeloggersPublic.server.PublicInterface.class.getMethod("getProjectDAO", new java.lang.Class[] {});
	    $method_getUserDAO_2 = se.kyh.ad10.timeloggersPublic.server.PublicInterface.class.getMethod("getUserDAO", new java.lang.Class[] {});
	    $method_getUserInfoDAO_3 = se.kyh.ad10.timeloggersPublic.server.PublicInterface.class.getMethod("getUserInfoDAO", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PublicInterfaceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getCustomerDAO()
    public se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO getCustomerDAO()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCustomerDAO_0, null, -7184050386370750675L);
	    return ((se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getProjectDAO()
    public se.kyh.ad10.timeloggers.server.dao.intf.ProjectDAO getProjectDAO()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getProjectDAO_1, null, 1954847168785850462L);
	    return ((se.kyh.ad10.timeloggers.server.dao.intf.ProjectDAO) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUserDAO()
    public se.kyh.ad10.timeloggers.server.dao.intf.UserDAO getUserDAO()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUserDAO_2, null, -6286218070247480195L);
	    return ((se.kyh.ad10.timeloggers.server.dao.intf.UserDAO) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUserInfoDAO()
    public se.kyh.ad10.timeloggers.server.dao.intf.UserInfoDAO getUserInfoDAO()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUserInfoDAO_3, null, 1534422575161262167L);
	    return ((se.kyh.ad10.timeloggers.server.dao.intf.UserInfoDAO) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
