// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class AttendedTimeDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.AttendedTimeDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_deleteAttendedTime_0;
    private static java.lang.reflect.Method $method_listAll_1;
    private static java.lang.reflect.Method $method_saveAttendedTime_2;
    
    static {
	try {
	    $method_deleteAttendedTime_0 = se.kyh.ad10.timeloggers.server.dao.intf.AttendedTimeDAO.class.getMethod("deleteAttendedTime", new java.lang.Class[] {int.class});
	    $method_listAll_1 = se.kyh.ad10.timeloggers.server.dao.intf.AttendedTimeDAO.class.getMethod("listAll", new java.lang.Class[] {});
	    $method_saveAttendedTime_2 = se.kyh.ad10.timeloggers.server.dao.intf.AttendedTimeDAO.class.getMethod("saveAttendedTime", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.AttendedTime.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public AttendedTimeDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of deleteAttendedTime(int)
    public boolean deleteAttendedTime(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deleteAttendedTime_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -5505340131809544773L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listAll()
    public java.util.List listAll()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listAll_1, null, 6533839432292156899L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveAttendedTime(AttendedTime)
    public boolean saveAttendedTime(se.kyh.ad10.timeloggers.server.entities.AttendedTime $param_AttendedTime_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveAttendedTime_2, new java.lang.Object[] {$param_AttendedTime_1}, 2968675187569999478L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
