// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class CustomerDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_changeCustomerActivityStatus_0;
    private static java.lang.reflect.Method $method_getAllCustomers_1;
    private static java.lang.reflect.Method $method_getCustomer_2;
    private static java.lang.reflect.Method $method_saveCustomer_3;
    
    static {
	try {
	    $method_changeCustomerActivityStatus_0 = se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO.class.getMethod("changeCustomerActivityStatus", new java.lang.Class[] {int.class});
	    $method_getAllCustomers_1 = se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO.class.getMethod("getAllCustomers", new java.lang.Class[] {});
	    $method_getCustomer_2 = se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO.class.getMethod("getCustomer", new java.lang.Class[] {int.class});
	    $method_saveCustomer_3 = se.kyh.ad10.timeloggers.server.dao.intf.CustomerDAO.class.getMethod("saveCustomer", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public CustomerDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of changeCustomerActivityStatus(int)
    public boolean changeCustomerActivityStatus(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_changeCustomerActivityStatus_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -5579867220615793704L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllCustomers()
    public java.util.List getAllCustomers()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllCustomers_1, null, 9130621405583481335L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getCustomer(int)
    public se.kyh.ad10.timeloggers.server.entities.Customer getCustomer(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCustomer_2, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -629177401375344422L);
	    return ((se.kyh.ad10.timeloggers.server.entities.Customer) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveCustomer(String)
    public boolean saveCustomer(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveCustomer_3, new java.lang.Object[] {$param_String_1}, 6797203735742508446L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
