// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class FeeInProjectDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.FeeInProjectDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_deleteFeeInProject_0;
    private static java.lang.reflect.Method $method_saveFeeInProject_1;
    
    static {
	try {
	    $method_deleteFeeInProject_0 = se.kyh.ad10.timeloggers.server.dao.intf.FeeInProjectDAO.class.getMethod("deleteFeeInProject", new java.lang.Class[] {int.class});
	    $method_saveFeeInProject_1 = se.kyh.ad10.timeloggers.server.dao.intf.FeeInProjectDAO.class.getMethod("saveFeeInProject", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.FeeInProject.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public FeeInProjectDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of deleteFeeInProject(int)
    public boolean deleteFeeInProject(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deleteFeeInProject_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -8631126123068433009L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveFeeInProject(FeeInProject)
    public boolean saveFeeInProject(se.kyh.ad10.timeloggers.server.entities.FeeInProject $param_FeeInProject_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveFeeInProject_1, new java.lang.Object[] {$param_FeeInProject_1}, -4356102727806254782L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
