// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class ProjetAdminLevelDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.ProjectAdminLevelDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getProjectAdminLevelName_0;
    private static java.lang.reflect.Method $method_saveProjectAdminLevel_1;
    
    static {
	try {
	    $method_getProjectAdminLevelName_0 = se.kyh.ad10.timeloggers.server.dao.intf.ProjectAdminLevelDAO.class.getMethod("getProjectAdminLevelName", new java.lang.Class[] {int.class});
	    $method_saveProjectAdminLevel_1 = se.kyh.ad10.timeloggers.server.dao.intf.ProjectAdminLevelDAO.class.getMethod("saveProjectAdminLevel", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.ProjectAdminLevel.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ProjetAdminLevelDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getProjectAdminLevelName(int)
    public java.lang.String getProjectAdminLevelName(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getProjectAdminLevelName_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 3265604746604850803L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveProjectAdminLevel(ProjectAdminLevel)
    public boolean saveProjectAdminLevel(se.kyh.ad10.timeloggers.server.entities.ProjectAdminLevel $param_ProjectAdminLevel_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveProjectAdminLevel_1, new java.lang.Object[] {$param_ProjectAdminLevel_1}, 8560211573274546739L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
