// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class RoleDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.RoleDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_deleteRole_0;
    private static java.lang.reflect.Method $method_getRoleName_1;
    private static java.lang.reflect.Method $method_saveRole_2;
    
    static {
	try {
	    $method_deleteRole_0 = se.kyh.ad10.timeloggers.server.dao.intf.RoleDAO.class.getMethod("deleteRole", new java.lang.Class[] {int.class});
	    $method_getRoleName_1 = se.kyh.ad10.timeloggers.server.dao.intf.RoleDAO.class.getMethod("getRoleName", new java.lang.Class[] {int.class});
	    $method_saveRole_2 = se.kyh.ad10.timeloggers.server.dao.intf.RoleDAO.class.getMethod("saveRole", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.Role.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RoleDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of deleteRole(int)
    public boolean deleteRole(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deleteRole_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -7626728907724435038L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getRoleName(int)
    public java.lang.String getRoleName(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getRoleName_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 1366637608625534243L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveRole(Role)
    public boolean saveRole(se.kyh.ad10.timeloggers.server.entities.Role $param_Role_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveRole_2, new java.lang.Object[] {$param_Role_1}, -5783857215331765399L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
