// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class SystemAdminLevelDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.SystemAdminLevelDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getAdminLevel_0;
    private static java.lang.reflect.Method $method_listAllLevels_1;
    private static java.lang.reflect.Method $method_setAdminLevel_2;
    
    static {
	try {
	    $method_getAdminLevel_0 = se.kyh.ad10.timeloggers.server.dao.intf.SystemAdminLevelDAO.class.getMethod("getAdminLevel", new java.lang.Class[] {int.class});
	    $method_listAllLevels_1 = se.kyh.ad10.timeloggers.server.dao.intf.SystemAdminLevelDAO.class.getMethod("listAllLevels", new java.lang.Class[] {});
	    $method_setAdminLevel_2 = se.kyh.ad10.timeloggers.server.dao.intf.SystemAdminLevelDAO.class.getMethod("setAdminLevel", new java.lang.Class[] {int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public SystemAdminLevelDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getAdminLevel(int)
    public int getAdminLevel(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAdminLevel_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 1647778344388097267L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listAllLevels()
    public java.util.List listAllLevels()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listAllLevels_1, null, -7199702416809318350L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setAdminLevel(int)
    public boolean setAdminLevel(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setAdminLevel_2, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 2049354182345551555L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
