// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class TimeLogDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_deleteTimeLog_0;
    private static java.lang.reflect.Method $method_getAllTimeLogsForUser_1;
    private static java.lang.reflect.Method $method_getAllTimeLogsForUserInProject_2;
    private static java.lang.reflect.Method $method_getAllTimelogsForProject_3;
    private static java.lang.reflect.Method $method_saveTimeLog_4;
    private static java.lang.reflect.Method $method_startTimeLog_5;
    private static java.lang.reflect.Method $method_stopTimeLog_6;
    
    static {
	try {
	    $method_deleteTimeLog_0 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("deleteTimeLog", new java.lang.Class[] {int.class});
	    $method_getAllTimeLogsForUser_1 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("getAllTimeLogsForUser", new java.lang.Class[] {int.class});
	    $method_getAllTimeLogsForUserInProject_2 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("getAllTimeLogsForUserInProject", new java.lang.Class[] {int.class, int.class});
	    $method_getAllTimelogsForProject_3 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("getAllTimelogsForProject", new java.lang.Class[] {int.class});
	    $method_saveTimeLog_4 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("saveTimeLog", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.Timelog.class});
	    $method_startTimeLog_5 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("startTimeLog", new java.lang.Class[] {int.class, int.class});
	    $method_stopTimeLog_6 = se.kyh.ad10.timeloggers.server.dao.intf.TimeLogDAO.class.getMethod("stopTimeLog", new java.lang.Class[] {int.class, java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TimeLogDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of deleteTimeLog(int)
    public boolean deleteTimeLog(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deleteTimeLog_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -1276578999796270866L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllTimeLogsForUser(int)
    public java.util.List getAllTimeLogsForUser(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllTimeLogsForUser_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 611252324246374232L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllTimeLogsForUserInProject(int, int)
    public java.util.List getAllTimeLogsForUserInProject(int $param_int_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllTimeLogsForUserInProject_2, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2)}, 4368314551533775072L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllTimelogsForProject(int)
    public java.util.List getAllTimelogsForProject(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllTimelogsForProject_3, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 4969172108486701065L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveTimeLog(Timelog)
    public boolean saveTimeLog(se.kyh.ad10.timeloggers.server.entities.Timelog $param_Timelog_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveTimeLog_4, new java.lang.Object[] {$param_Timelog_1}, -7022294309874660618L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of startTimeLog(int, int)
    public boolean startTimeLog(int $param_int_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_startTimeLog_5, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2)}, -723950890948970183L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of stopTimeLog(int, String, String)
    public boolean stopTimeLog(int $param_int_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_stopTimeLog_6, new java.lang.Object[] {new java.lang.Integer($param_int_1), $param_String_2, $param_String_3}, -203951842237712128L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
