// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class UserDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.UserDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_activateUser_0;
    private static java.lang.reflect.Method $method_deleteUser_1;
    private static java.lang.reflect.Method $method_getAllUsers_2;
    private static java.lang.reflect.Method $method_getName_3;
    private static java.lang.reflect.Method $method_getUserById_4;
    private static java.lang.reflect.Method $method_getUserRolesInProject_5;
    private static java.lang.reflect.Method $method_getUsersForProject_6;
    private static java.lang.reflect.Method $method_inactivateUser_7;
    private static java.lang.reflect.Method $method_login_8;
    private static java.lang.reflect.Method $method_saveUser_9;
    
    static {
	try {
	    $method_activateUser_0 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("activateUser", new java.lang.Class[] {int.class});
	    $method_deleteUser_1 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("deleteUser", new java.lang.Class[] {int.class});
	    $method_getAllUsers_2 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("getAllUsers", new java.lang.Class[] {});
	    $method_getName_3 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("getName", new java.lang.Class[] {int.class});
	    $method_getUserById_4 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("getUserById", new java.lang.Class[] {int.class});
	    $method_getUserRolesInProject_5 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("getUserRolesInProject", new java.lang.Class[] {int.class, int.class});
	    $method_getUsersForProject_6 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("getUsersForProject", new java.lang.Class[] {int.class});
	    $method_inactivateUser_7 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("inactivateUser", new java.lang.Class[] {int.class});
	    $method_login_8 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("login", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_saveUser_9 = se.kyh.ad10.timeloggers.server.dao.intf.UserDAO.class.getMethod("saveUser", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.User.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public UserDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of activateUser(int)
    public boolean activateUser(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_activateUser_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 7746587555032471136L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteUser(int)
    public void deleteUser(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteUser_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -6557420434786712684L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAllUsers()
    public java.util.List getAllUsers()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAllUsers_2, null, -8085499765165193171L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getName(int)
    public java.lang.String getName(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getName_3, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 2989299904973873140L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUserById(int)
    public se.kyh.ad10.timeloggers.server.entities.User getUserById(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUserById_4, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -8897046412658324667L);
	    return ((se.kyh.ad10.timeloggers.server.entities.User) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUserRolesInProject(int, int)
    public java.util.List getUserRolesInProject(int $param_int_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUserRolesInProject_5, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2)}, -3312216099722939710L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUsersForProject(int)
    public java.util.List getUsersForProject(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUsersForProject_6, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -5754635574808584538L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of inactivateUser(int)
    public boolean inactivateUser(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_inactivateUser_7, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 3871210283086686399L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of login(String, String)
    public se.kyh.ad10.timeloggers.server.entities.User login(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_login_8, new java.lang.Object[] {$param_String_1, $param_String_2}, -1877464530628401182L);
	    return ((se.kyh.ad10.timeloggers.server.entities.User) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveUser(User)
    public boolean saveUser(se.kyh.ad10.timeloggers.server.entities.User $param_User_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveUser_9, new java.lang.Object[] {$param_User_1}, 6325820868871449676L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
