// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package se.kyh.ad10.timeloggers.server.dao.impl;

public final class UserInfoDAOImpl_Stub
    extends java.rmi.server.RemoteStub
    implements se.kyh.ad10.timeloggers.server.dao.intf.UserInfoDAO, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_deleteUserInfo_0;
    private static java.lang.reflect.Method $method_listUserInfoByUser_1;
    private static java.lang.reflect.Method $method_saveUserInfo_2;
    
    static {
	try {
	    $method_deleteUserInfo_0 = se.kyh.ad10.timeloggers.server.dao.intf.UserInfoDAO.class.getMethod("deleteUserInfo", new java.lang.Class[] {int.class});
	    $method_listUserInfoByUser_1 = se.kyh.ad10.timeloggers.server.dao.intf.UserInfoDAO.class.getMethod("listUserInfoByUser", new java.lang.Class[] {int.class});
	    $method_saveUserInfo_2 = se.kyh.ad10.timeloggers.server.dao.intf.UserInfoDAO.class.getMethod("saveUserInfo", new java.lang.Class[] {se.kyh.ad10.timeloggers.server.entities.UserInfo.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public UserInfoDAOImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of deleteUserInfo(int)
    public boolean deleteUserInfo(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deleteUserInfo_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -5782577694514905314L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listUserInfoByUser(int)
    public java.util.List listUserInfoByUser(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listUserInfoByUser_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 4967762793120437673L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of saveUserInfo(UserInfo)
    public boolean saveUserInfo(se.kyh.ad10.timeloggers.server.entities.UserInfo $param_UserInfo_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_saveUserInfo_2, new java.lang.Object[] {$param_UserInfo_1}, -7459315626291778570L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
